In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

In [3]:
df = pd.read_csv("solar_system.csv")
df

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [4]:
print("Shape:", df.shape)
print("Rows and columns:", df.shape[0], df.shape[1])

print("\nFirst five rows:")
print(df.head())

print("\nLast five rows:")
print(df.tail())

print("\nColumn names:")
print(df.columns)

print("\nRow names:")
print(df.index)

Shape: (20, 11)
Rows and columns: 20 11

First five rows:
                Attribute Mercury  Venus  Earth   Moon   Mars Jupiter  Saturn  \
0          Mass (10^24kg)   0.330   4.87   5.97  0.073  0.642    1898     568
1           Diameter (km)    4879  12104  12756   3475   6792  142984  120536
2        Density (kg/m^3)    5429   5243   5514   3340   3934    1326     687
3         Gravity (m/s^2)     3.7    8.9    9.8    1.6    3.7    23.1     9.0
4  Escape Velocity (km/s)     4.3   10.4   11.2    2.4    5.0    59.5    35.5

  Uranus Neptune   Pluto
0   86.8     102  0.0130
1  51118   49528    2376
2   1270    1638    1850
3    8.7    11.0     0.7
4   21.3    23.5     1.3

Last five rows:
                  Attribute Mercury Venus Earth Moon  Mars  Jupiter   Saturn  \
15     Mean Temperature (C)     167   464    15  -20   -65     -110     -140
16  Surface Pressure (bars)       0    92     1    0  0.01  Unknown  Unknown
17          Number of Moons       0     0     1    0     2       95      274
18             Ring System?      No    No    No   No    No      Yes      Yes
19   Global Magnetic Field?     Yes    No   Yes   No    No      Yes      Yes

     Uranus  Neptune    Pluto
15     -195     -200     -225
16  Unknown  Unknown  0.00001
17       28       16        5
18      Yes      Yes       No
19      Yes      Yes  Unknown

Column names:
Index(['Attribute', 'Mercury', 'Venus', 'Earth', 'Moon', 'Mars', 'Jupiter',
       'Saturn', 'Uranus', 'Neptune', 'Pluto'],
      dtype='object')

Row names:
RangeIndex(start=0, stop=20, step=1)

In [5]:
df.iloc[:, 0]

0                  Mass (10^24kg)
1                   Diameter (km)
2                Density (kg/m^3)
3                 Gravity (m/s^2)
4          Escape Velocity (km/s)
5         Rotation Period (hours)
6           Length of Day (hours)
7     Distance from Sun (10^6 km)
8            Perihelion (10^6 km)
9              Aphelion (10^6 km)
10          Orbital Period (days)
11        Orbital Velocity (km/s)
12      Orbital Inclination (deg)
13           Orbital Eccentricity
14       Obliquity to Orbit (deg)
15           Mean Temperature (C)
16        Surface Pressure (bars)
17                Number of Moons
18                   Ring System?
19         Global Magnetic Field?
Name: Attribute, dtype: object

In [7]:
df = df.set_index("Attribute")
df

,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
Attribute,,,,,,,,,,
Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
Number of Moons,0,0,1,0,2,95,274,28,16,5
Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [10]:
orbital_period.head()

Mercury     88.0
Venus      224.7
Earth      365.2
Moon        27.3
Mars       687.0
Name: Orbital Period (days), dtype: float64

In [11]:
semi_major_axis = (perihelion + aphelion) / 2
semi_major_axis

Mercury      57.9000
Venus       108.2000
Earth       149.6000
Moon          0.3845
Mars        228.0000
Jupiter     778.5000
Saturn     1432.0500
Uranus     2867.0500
Neptune    4515.0000
Pluto      5906.3500
dtype: float64

In [12]:
semi_major_axis_row = pd.Series(semi_major_axis, name="Semi-major axis (10^6 km)")
df = pd.concat([df, semi_major_axis_row.to_frame().T])
df

,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
Number of Moons,0,0,1,0,2,95,274,28,16,5
Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown
Semi-major axis (10^6 km),57.9,108.2,149.6,0.3845,228.0,778.5,1432.05,2867.05,4515.0,5906.35

In [13]:
print("New shape:", df.shape)

New shape: (21, 10)

In [ ]:
plt.scatter(semi_major_axis, orbital_period, label="Planets")

plt.xlabel("Semi-major axis (10^6 km)")
plt.ylabel("Orbital period (days)")
plt.title("Semi-major Axis vs Orbital Period")
plt.legend()

plt.show()